config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      get :out_for_delivery, to: 'orders#out_for_delivery'
      get :delivered, to: 'orders#delivered'
    end
  end
  devise_for :users, :controllers => {:registrations => "user/registrations"}
  root 'welcome#index'

  get 'terms', to: 'welcome#terms'
  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  mount_uploader :attachment, AttachmentUploader

  validates :title, presence: true, length: {minimum: 3, maximum: 60}
  validates :location, presence: true
  validates :delivery_time, presence: true
  validates :attachment, presence: true
  validates :details, length: { maximum: 100}
  # validates :page_count, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  VALID_NAME_REGEX = /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/
  validates :first_name, presence: true, format: { with: VALID_NAME_REGEX}
  validates :last_name, presence: true, format: { with: VALID_NAME_REGEX}
  validates :phone_number, presence: true
  validates :customer_type, presence: true
  validates :terms_and_conditions, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false}, format: {with:
   /\b[A-Z0-9._%a-z\-]+@mail\.endicott\.edu|@endicott\.edu\z/, message: "must be an Endicott email"}
  validates :gender, presence: true
  validates :venmo_name, presence: true


  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Annonymous"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/orders_controller.rb
require 'pdf-reader'
require 'fileutils'
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.paginate(page: params[:page], per_page:11)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.status = "Waiting for Venmo Payment"
    if @order.delivery_time == "Express"
      @order.price = 4.00
    elsif @order.delivery_time == "Overnight (before 7AM)"
      @order.price = 3.00
    elsif @order.delivery_time == "7:00-8:00PM"
      @order.price = 2.00
    elsif  @order.delivery_time == "10:00-11:00PM"
      @order.price = 2.50
    end

    # attachment = @order.attachment
    # PDF::Reader.open("#{Rails.root}/public"+attachment.to_s) do |reader|
    #   # puts reader.page_count
    #   pages = reader.page_count.to_int
    #   @order.page_count = pages
    #   page_price = pages * (0.05)
    #   @order.price += page_price
    #   # puts @order.price
    # end

    respond_to do |format|
      if @order.save
        OrderMailer.order_email(@order, @order.user).deliver_now
        OrderMailer.order_admin_email(@order, @order.user).deliver_now
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def out_for_delivery
    @order = Order.find(params[:id])
    @order.status = "Out for Delivery"
    userID = @order.user_id
    user = User.find(userID)
    if @order.save
      OrderMailer.payment_recieved_admin_email(@order, @order.user).deliver_now
      OrderMailer.payment_recieved_user_email(@order, @order.user).deliver_now
      redirect_to orders_url, notice: 'Order is out for delivery, Payment was recieved'
    end
  end

  def delivered
    @order = Order.find(params[:id])
    @order.status = "Delivered"
    userID = @order.user_id
    user = User.find(userID)
    if @order.save
      OrderMailer.order_delivered_admin_email(@order, @order.user).deliver_now
      OrderMailer.order_delivered_user_email(@order, @order.user).deliver_now
      redirect_to orders_url, notice: 'Order was successfully delivered.'
    end
    puts @order.attachment.to_s
    File.delete("#{Rails.root}/public"+@order.attachment.to_s)
    puts @order.attachment.to_s
    FileUtils.rm_rf("#{Rails.root}/public/uploads/order/attachment/"+@order.id.to_s)
    puts @order.attachment.to_s

  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:title, :location, :delivery_time, :details, :attachment, :status, :user_id)
    end

    def require_same_user
      if current_user != @order.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete you own orders"
        redirect_to orders_path
      end
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number,
    :customer_type, :plan_type, :terms_and_conditions, :gender, :venmo_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number,
    :customer_type,:plan_type, :terms_and_conditions, :gender, :venmo_name])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :terms, :about, :contact]

  def index
  end

  def terms
    #code
  end

  def about
    #code
  end

  def contact
    #code
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Didact Gothic' rel='stylesheet'>
    <title><%= content_for?(:title) ? yield(:title) : "Gull Paper Express" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= image_tag "Bird-Only.png", height: 40, width: 40, class: "navbar-left" %>
        <%= link_to 'Gull Paper Express', root_path, class:"navbar-brand", id: "logo" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if current_user%>
            <li><%= link_to "Orders", orders_path, id: "nav-link"%></li>
            <li><%= link_to "New Order", new_order_path, id: "nav-link"%></li>
            <% end %>
            <li><%= link_to "About", about_path, id: "nav-link"%></li>
            <li><%= link_to "Contact Us", contact_path, id: "nav-link"%></li>
          </ul>
          <ul class="nav navbar-right col-md-4">
            <% if current_user%>
            <li class="col-md-6 user-name">
            <%= link_to (truncate(current_user.email, length: 28)).html_safe,
              edit_user_registration_path, class: 'btn btn-xs btn-success', title: 'Edit Profile' %>
            </li>
            <li class="col-md-1"> </li>
            <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path,
              class: 'btn btn-xs btn-success', title: 'Logout', :method => :delete) %></li>
            <% else %>
            <li class="col-md-4 pull-right">
            <%= link_to('Sign In', new_user_session_path, class: 'btn btn-success', title: 'Sign In') %>
            </li>
            <% end %>
            </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <br>
        <p>&copy; Gull Paper Express 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/orders/_form.html.erb
<%= bootstrap_form_for @order, :html => { multipart: true, :class => "form-horizontal order" } do |f| %>

  <% if @order.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_field :title, label: { text: "Title | Of order or paper, so we can make sure you are.. you " }, autofocus: true, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.file_field :attachment, label: {text:"Attachment | PDF only for security, stay safe out there "}, :class => 'form-control' %>
      <p><a href="https://www.youtube.com/watch?v=tIS8Wop_7H4">Microsoft Word: Save as PDF</a></p>
      <p><a href="https://youtu.be/0kADxcMcjAY?t=45s">Pages for Mac: Save as PDF</a></p>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-10">
      <%= f.select :location, ['Alhambra', 'Bayview', 'Beacon', 'Birchmont',
         'Brindle', 'Brooks', 'Endicott', 'Essex', 'Farm House',
         'Frates', 'Gloucester', 'Hale', 'Hamilton', 'Hawthorne', 'Kennedy', 'LSB',
         'Manchester', 'Marblehead', 'Post Center', 'Standish', 'Reynolds', 'Rockport',
         'Rogers', 'Stoneridge', 'Tower', 'Trexler', 'VPAC', 'Wenham', 'Williston',
         'Winthrop', 'Woodside'],label: { text: "Location | Where would you like the paper delivered? " }, :prompt => ["Select One"],  :class => 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.select :delivery_time, ['Express', 'Overnight (before 7AM)', '7:00-8:00 PM', '10:00-11:00 PM'],
      label: { text: "Delivery Time | Orders submitted after 11PM can not be delivered during 8-10... yet " }, :prompt => ["Select One"], :class => 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.text_area :details, label: { text: "Details | Room #, special requests, *front door is open*, etc..." }, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <h1 id="price">$</h1><br><br>
      <h4 id="payment-reminder">Send Via Venmo to @gullpaperexpress</h4><br>
      <h4 id="payment-reminder">Once Payment is Recieved Your Order will be Processed</h4>
      <br><br>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg col-lg-10">
      <%= f.submit nil, :class => 'btn btn-success' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                orders_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
<div class="col-lg col-lg-10">
  <%= link_to t('.destroy', :default => "Delete Order"),
                order_path(@order),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
</div>

app/views/orders/index.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= link_to "New Order",
            new_order_path,
            :class => 'btn btn-success btn-lg' %><br><br>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th>User</th>
      <th><%= model_class.human_attribute_name(:delivery_time) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each.reverse_each do |order| %>
    <% userID = order.user_id %>
    <% user = User.find(userID) %>
      <tr>
        <td><%= link_to order.title, order_path(order) %></td>
        <td><%= user.first_name%> <%= user.last_name.chars.first%></td>
        <td><%= order.delivery_time %></td>
        <% if order.status == "Waiting for Venmo Payment" %>
          <td class="pending"><b><%= order.status %></b></td>
        <% elsif order.status == "Out for Delivery" %>
          <td class="out"><b><%= order.status %></b></td>
        <% else %>
          <td class="delivered"><b><%= order.status %></b></td>
        <% end %>
        <td><%= time_ago_in_words(order.created_at) %> ago</td>
        <td>
        <% if current_user == order.user || current_user.admin? %>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      order_path(order), :class => 'btn btn-info btn-xs' %>
        <% end %>
        <% if current_user.admin? %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_order_path(order), :class => 'btn btn-warning btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      order_path(order),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <%= link_to 'Out for Delivery', out_for_delivery_order_path(order), class: 'btn btn-primary btn-xs sign-up',
          data: {confirm: 'Are you sure this is printed and ready for delivery?'} %>
          <% if order.status == "Out for Delivery"%>
            <%= link_to 'Delivered', delivered_order_path(order), class: 'btn btn-success btn-xs sign-up',
            data: {confirm: 'Are you sure this is delivered?'} %>
          <% end %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div align="center">
  <%= will_paginate %>
</div>

app/views/orders/new.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/show.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <h4><dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt></h4>
  <h4><dd><%= @order.title %></dd></h4>
  <h4><dt><strong><%= model_class.human_attribute_name(:delivery_time) %>:</strong></dt></h4>
  <h4><dd><%= @order.delivery_time %></dd></h4>
  <% if current_user == @order.user || current_user.admin?  %>
    <h4><dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt></h4>
    <h4><dd><%= @order.location %></dd></h4>
    <h4><dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt></h4>
    <h4><dd><%= @order.details %></dd></h4>
    <h4><dt class="delivered"><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt></h4>
    <h4><dd class="delivered">$<%= '%.2f' % @order.price %></dd></h4>
  <% end %>
  <h4><dt><strong><%= model_class.human_attribute_name(:attachment) %>:</strong></dt></h4>
  <h4><dd>Recieved</dd></h4>
  <h4><dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt></h4>
  <% if @order.status == "Waiting for Venmo Payment" %>
    <h4><dd class="pending"><%= @order.status %></dd></h4>
  <% elsif @order.status == "Out for Delivery" %>
    <h4><dd class="out"><%= @order.status %></dd></h4>
  <% else %>
    <h4><dd class="delivered"><%= @order.status %></dd></h4>
  <% end %>
  <h4><dt><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt></h4>
  <h4><dd><%= time_ago_in_words(@order.created_at)%> ago</dd></h4>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              orders_path, :class => 'btn btn-info'  %>
<% if current_user == @order.user && @order.status == "Waiting for Venmo Payment" %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_order_path(@order), :class => 'btn btn-warning' %>

<% end %>
<% if current_user.admin? %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_order_path(@order), :class => 'btn btn-warning' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                order_path(@order),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  <%= link_to 'Out for Delivery', out_for_delivery_order_path(@order), class: 'btn btn-primary btn-md sign-up', data: {confirm: 'Are you sure this is printed and ready for delivery?'}  %>
<% end %>
<% if current_user.admin? && @order.status == "Out for Delivery"%>
  <%= link_to 'Delivered', delivered_order_path(@order), class: 'btn btn-success btn-md sign-up', data: {confirm: 'Are you sure this is delivered?'} %>
<% end %>
<br><br>

app/views/welcome/about.html.erb
<div class="jumbotron col-lg-12" id="about-jumbo">
  <br><br><br><br><br><br><br><br>
  <h1>Gull Paper Express</h1>
  <br><br><br><br><br><br><br><br>
</div>
<div class="col-lg-12  plan", id="about-border">
  <p align="center"><%= image_tag "GPELogo.png" %></p>
    <div class="features">
      <ul>
        <h2 align="left"><b>Our Mission</b><br></h2><h5 align="left">Deliver papers
           to students and faculty as quickly as possible so they can do more of
            whatever they enjoy doing or focus on what they need to.</h5><br>

        <h2 align="left"><b>How it Works</b><br></h2><p align="left">Signing up for a Gull Paper Delivery
           account is easy and only takes a minute. Once you're signed in, you'll
            recieve a confirmation email and will then have immediately have access to all the features on the site.
             You can simply click on the Orders tab and fill out the order title, location,
              delivery time, additional details if necesary, attach your file (as PDF for security reasons), and click submit.
               You will recieve a confirmation email that your order was successfully
                submitted. Pay via Venmo and your order will be printed and on the way. It arrive exactly where and when you selected, guarenteed.
                 </p><br>



         <h1 align="center">How We Improve Your Life</h1><br>
           <div class="features">
               <h3 align="center" >
                 We Print & Rapidly Deliver All of Your Paper Needs All Semester Long At The Lowest Possible Price
               </h3>
               <h4 align="center" >24 hours a day | 7 days a week</h4>
               <br>
               <div align="left">
                 <ul>
                   <li><h4>Easily submit your order and then; go to bed, watch Netflix, or live your life as you normally would</h4></li>
                   <li><h4>We can slip it under your door so when you return or wake up it's right there waiting for you</h4></li>
                   <li><h4>You can go to bed earlier, wake up later, and walk to class paper in hand with no worries</h4></li>
                   <li><h4>Show up to class without your paper? Don't sweat it, call us or submit an emergency order, it'll be there in 20 minutes</h4></li>
                   <li><h4>Sign Up for Venmo and you're ready to go.</h4></li>
                 </ul>
               </div>
                 <h1 align="center">First Order $2</h1>
           </div>
           <br>
      </ul>
    </div>
    <p align="center"><b>Images Credit:</b></p>
    <p align="center">Luke Pepper | <a href="http://www.lpepper9.com/">Website</a> | <a href="https://www.instagram.com/lpepper9/">Instagram</a></p>
    <br>
    <p align="center">
      <%= link_to 'Home', root_path, class: 'btn btn-primary btn-lg sign-up', id: "btn-sign-up" %>
    </p>
  </div>

app/views/welcome/contact.html.erb
<div class="jumbotron col-lg-12" id= "contact-jumbo">
  <br><br><br><br><br><br><br><br>
  <h1>Gull Paper Express</h1>
  <br><br><br><br><br><br><br><br>
</div>
<div class="col-lg-12  plan", id="contact-border">
  <p align="center"><%= image_tag "GPELogo.png" %></p>
    <div class="features">
      <ul>
        <h4 align="center"><b>Special request? Question? Comment?</b><br></h4>
        <br>
        <h4 align="center">Email: <a href="">gullpaperdelivery@gmail.com</a></h4>
        <h4 align="center">Instagram: <a href="https://www.instagram.com/gullpaperdelivery/">gullpaperdelivery</a></h4>
        <h4 align="center">Facebook: <a href="https://www.facebook.com/Gull-Paper-Delivery-163310514234235/">Gull Paper Delivery</a></h4>
      </ul>
    </div>
    <br>
    <p align="center">
      <%= link_to 'Home', root_path, class: 'btn btn-primary btn-lg sign-up', id: "btn-sign-up" %>
    </p>
  </div>

app/views/welcome/index.html.erb
<link href='https://fonts.googleapis.com/css?family=Exo' rel='stylesheet'>
<div class="jumbotron col-lg-12">
  <br><br><br>
  <h1>Welcome to Gull Paper Express</h1>
  <h3>The Campus Delivery Service you Always Wanted</h3>
  <br>
  <p>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success btn-lg sign-up', id: "btn-sign-up" %>
  </p>
  <br><br>
</div>

<div class="home-image-left col-lg-4">
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>
<div class="home-image-middle col-lg-4">
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>
<div class="home-image-right col-lg-4">
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>

<div align="center" class="row">
  <div class="plans clearfix">
    <div class="col-lg-12">
      <br>
    </div>
  </div>
</div>

app/views/welcome/terms.html.erb
<div class="jumbotron col-lg-12" id= "terms-jumbo">
  <br><br><br><br><br><br><br><br><br><br><br>
  <h1>Gull Paper Express</h1>
  <br><br><br><br><br><br><br><br><br><br><br>
</div>
<div class="col-lg-12  plan", id="terms-border" >
  <p align="center"><%= image_tag "GPELogo.png" %></p><br><br><br>
  <h2 align="center">Terms and Conditions</h2><br><br>
  <ul>
    <li><p> Gull Paper Express workers will never enter the dorm room of any student.</p></li>
    <li><p>We are not responsible for students handing in papers on time.</p></li>
    <li><p>Papers are not saved and emails containing attachments will be deleted weekly.</p></li>
    <li><p>Gull Paper Express is not responsible for failure to deliver due to printer issues,
    however, customers will be notified in any such situation.</p></li>
    <li><p>User accounts and order submissions with excessively vulgar or inappropriate language will be deleted</p></li>
    <li><p>This is a great service for the campus, use it use it, dont abuse it</p></li>
    <li><p>Terms and Conditions are subject to change</p></li>
    <br><br>
  </ul>
</div>